### ISSUE TITLE
Definir formato do título da issue de cada tradução.

### ISSUE THREAD

**Issue by FelipeCardoso89** [CocoaHeadsBrasil/the-swift-programming-language-in-portuguese-br#14]
O que acham de usarmos um padrão no título de cada issue de tradução que descreve até o mais específico tópico que será traduzido? Assim os trechos de tradução ficariam menores, facilitando o processo de review de cada um, e mais pessoas poderiam contribuir para um mesmo capítulo.

Ex: 
[Tradução] [Capítulo] - [Sessão] - [Tópico] - ...
[Tradução] Bem vindo ao Swift - Um tour pelo Swift - Valores Simples

**Comment by barbosa** [comment]
O problema é que não sei se conseguimos essa granularidade. Teria que ver como fica a estrutura de pastas e arquivos markdown caso fôssemos dividir ainda mais do que já está, dado que estamos montando a estrutura já nos moldes do Gitbook.

Não conheço muito do Gitbook pra responder se dá ou não. Talvez o @walmyrcarvalho possa dizer melhor.

**Comment by walmyrcarvalho** [comment]
@FelipeCardoso89 Então, acho que a gente tá usando essa nomenclatura só pras issues mesmo, dentro do GitBook ele usa o formato abaixo:

```
* [Capítulo 1](pasta_capitulo1/capitulo1.md)
    * [Sessão 1](pasta_capitulo1/sessao11.md)
```

Eu também nunca tentei fazer uma terceira ramificação (por tópico, como você sugeriu), mas acho que o GitBook resolve bem pro caso de Capítulos e Sessões.

Eu vou olhar com mais calma isso e te aviso, se for possível talvez seja uma boa, mas não sei se o GitBook fornece isso.

**Comment by Viniciuscarvalho** [comment]
@FelipeCardoso89 Pelo que li da documentação do Gitbook, ele só divide em capítulos e sub-capítulos, foi como havia colocado no Wiki, não sei se seria possível essa terceira ramificação, mas posso estar errado também :)

link que referência isso - https://help.gitbook.com/format/chapters.html

**Comment by barbosa** [comment]
@FelipeCardoso89 

Definimos um formato de título para issues de traduções e PRs de revisões. Foi adicionado no README.

Sobre o tamanho dos trechos de revisão, o @talesp sugeriu no Slack de ir fazendo revisões parciais. Feito o PR, a pessoa avisa que é temporário e quem quiser vai revisando. Daí a pessoa vai atualizando o PR com mais texto e continuamos o fluxo de revisão.

O que acha?

**Comment by FelipeCardoso89** [comment]
Eu acho uma ótima ideia, com certeza vai tornar a revisão mais dinâmica e
menos cansativa. Alguns capítulos tem algo em torno de 50 páginas, é muito
pra revisar de uma vez.
Em seg, 21 de dez de 2015 às 13:50, Gustavo Barbosa <
notifications@github.com> escreveu:

**Comment by barbosa** [comment]
Combinado então. Vou fechar essa issue :+1: 

Se achar que ainda falta alguma coisa pra definir, fique à vontade para reabrir.
