### ISSUE TITLE
Descrever no README os padrões de escrita

### ISSUE THREAD

**Issue by barbosa** [CocoaHeadsBrasil/the-swift-programming-language-in-portuguese-br#19]
- Palavras em inglês que não forem traduzidas, colocar em itálico;
- Código inline colocar entre crases para ficar alo como: defina um constante de tipo `String` e valor `"John Appleseed"`;
- Código em bloco deve conter syntax highlight do Swift;
- Traduzir termo técnico apenas se fizer sentido. Se for prejudicar o entendimento, é preferível manter o termo original. ex.: Closures;
- Notas de rodapé devem ser criadas como quote do markdown, usando o sinal de `>` na frente

**Comment by txaiwieser** [comment]
Closures*

**Comment by barbosa** [comment]
:+1:

**Comment by Viniciuscarvalho** [comment]
@barbosa é para melhorar o README com essas dicas ae?

**Comment by barbosa** [comment]
@Viniciuscarvalho isso. Vou fazer um PR adicionando esses itens. Se alguém lembrar de mais algum, a gente adiciona.
