### ISSUE TITLE
Buscar tipo de licença adequada para o repositório

### ISSUE THREAD

**Issue by Viniciuscarvalho** [CocoaHeadsBrasil/the-swift-programming-language-in-portuguese-br#2]
Search for a suitable type for this kind of repository.

**Comment by barbosa** [comment]
Acho que não tem problema criar issues e comentários em português para esse projeto, visto que o público alvo é nacional.

**Comment by barbosa** [comment]
O que acha, @Viniciuscarvalho ?

**Comment by Viniciuscarvalho** [comment]
Pois é, acho que é o costume criar em inglês, vamos trocar tudo para português desde as issues também :) @barbosa

**Comment by barbosa** [comment]
Os chineses usam nenhuma. Ou melhor, a [WTFPL](https://en.wikipedia.org/wiki/WTFPL).

Achei estranho, dado que o conteúdo original pertence à Apple. Mas de qualquer forma era bom talvez entrar em contato com eles antes de ter uma decisão sobre isso.

**Comment by talesp** [comment]
Porque não manter a original?
https://creativecommons.org/licenses/by/4.0/

Aqui também tem um pequeno seletor de variações da CC 4.0:
http://creativecommons.org/choose/

**Comment by walmyrcarvalho** [comment]
Eu voto pela CC também, acho que atende o propósito do projeto. :)

**Comment by Viniciuscarvalho** [comment]
Acredito que a CC atende melhor também :+1:

**Comment by Viniciuscarvalho** [comment]
Alguém mais tem outro tipo de licença para propor?

**Comment by ythecombinator** [comment]
+1 pela _CC BY 4.0_

**Comment by barbosa** [comment]
Coloca lá, @Viniciuscarvalho ?

**Comment by Viniciuscarvalho** [comment]
Na hora, vou colocar agora @barbosa

**Comment by Viniciuscarvalho** [comment]
:+1:
