### ISSUE TITLE
Mudar Initialization p/ Inicialização e Deinitialization p/ Deinicialização?

### ISSUE THREAD

**Issue by renan976** [CocoaHeadsBrasil/the-swift-programming-language-in-portuguese-br#24]
Que tal realizar essas mudanças no Sumário? Faria sentido? Acho que para o leigo em programação e inglês, seja bem mais fácil ler inicializadores do que initializers.

**Comment by barbosa** [comment]
Concordo com Initialization -> Inicialização, @renan976 

Sobre "Deinicialização": a palavra existe? Procurei aqui rápido e não encontrei. Por isso a dúvida.

**Comment by renan976** [comment]
@barbosa, Deinicialização realmente não existe, dessa forma acho que seria melhor manter no inglês. O que achas? É que geralmente quando estou explicando para alguém sobre esse conceito, costumo falar o termo no português do que no inglês.

**Comment by barbosa** [comment]
"Destruição" faz sentido?

cc/ @talesp

**Comment by renan976** [comment]
@barbosa achei destruição um termo bastante agressivo kk

Não estamos de fato destruindo a instância, apenas dizendo através do deinit o que deve ser feito antes dela ser desalocada pelo ARC ao atribuirmos nulo à uma optional.

Desalocador também acho que seria um termo bastante estranho, e acho que nem existe também.

Vou pensar em outros termos e por enquanto vou mantendo _Deinitializers_

**Comment by FelipeCardoso89** [comment]
"Desconstrução, Desconstrutores, Desconstruir" talvez.

On Mon, Dec 21, 2015 at 2:34 PM, Gustavo Barbosa notifications@github.com
wrote:

> "Destruição" faz sentido?
> 
> cc/ @talesp https://github.com/talesp
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CocoaHeadsBrasil/the-swift-programming-language-in-portuguese-br/issues/24#issuecomment-166352528
> .

## 

Felipe A. Cardoso
iOS Developer, BS. in Computer Science and MS. in Physics & Astronomy.

**Comment by barbosa** [comment]
Pois é. Eu gosto de como C++ chama e, se não estou enganado, os métodos tem o mesmo propósito: "constructor" e "destructor".

http://www.tutorialspoint.com/cplusplus/cpp_constructor_destructor.htm

**Comment by barbosa** [comment]
@FelipeCardoso89 gostei de "desconstrução".

**Comment by talesp** [comment]
Também gostei, mas eu colocaria assim no começo da sessão:
No original:
“A _deinitializer_ is called immediately before a class instance is deallocated. ”
Na tradução:
“Um _desconstrutor_ - do original _deinitializer_ - é chamado imediatamente antes de uma instância de uma classe ser desalocada”

**Comment by renan976** [comment]
@talesp, curti essa tua sugestão :)

Valeu pessoal! Vou seguir traduzindo dessa forma então.

**Comment by Viniciuscarvalho** [comment]
Tudo certo então? Posso fechar a task @renan976 ?

**Comment by renan976** [comment]
@Viniciuscarvalho, pode fechar sim ;)

**Comment by Viniciuscarvalho** [comment]
:+1:
