### ISSUE TITLE
Guia da Linguagem - Nested Types

### ISSUE THREAD

**Issue by lourenco-marinho** [CocoaHeadsBrasil/the-swift-programming-language-in-portuguese-br#38]
Boa tarde :)

Faço parte do iOSDev lá no Slack e gostaria de contribuir com a tradução desse capítulo.

**Comment by txaiwieser** [comment]
Ja tem issue desse capítulo, estou terminando quase

**Comment by Viniciuscarvalho** [comment]
Da uma olhada nas issues @lourenco-marinho :+1: Pode pegar outra se quiser!

**Comment by lourenco-marinho** [comment]
Putz @txaidw foi mal passou despercebido 😅
Vou pegar outro capítulo @Viniciuscarvalho e fechar essa issue aqui.

Valeu :)
