### ISSUE TITLE
Adicionar imagem para visualizar o preview do GitBook

### ISSUE THREAD

**Issue by Viniciuscarvalho** [CocoaHeadsBrasil/the-swift-programming-language-in-portuguese-br#4]

**Comment by Viniciuscarvalho** [comment]
![preview_gitbook](https://cloud.githubusercontent.com/assets/4513004/11879695/a3171faa-a4db-11e5-9beb-b803764fb4c8.png)

Colocar esta imagem no Wiki do Gitbook.

**Comment by barbosa** [comment]
Qual era a ideia dessa issue, @Viniciuscarvalho ?

**Comment by Viniciuscarvalho** [comment]
Colocar a prévia de como estava o livro no Gitbook, vou adicionar lá no Wiki @barbosa
