### ISSUE TITLE
Adicionar instruções sobre como contribuir usando a interface web do GitBook.

### ISSUE THREAD

**Issue by FelipeCardoso89** [CocoaHeadsBrasil/the-swift-programming-language-in-portuguese-br#5]
GitBook oferece interface web para edição de documentos.
Isso pode facilitar o processo de contribuição em geral.

**Comment by Viniciuscarvalho** [comment]
E como ficaria essa edição Felipe, pode nos mostrar um exemplo?

**Comment by FelipeCardoso89** [comment]
Quem quiser colaborar pode ligar o fork que fez a uma conta no site do GitBook (https://www.gitbook.com) e utilizar a interface gráfica, e ferramentas de edição, para contribuir com o documento.
Ao terminar o trecho que traduziu é só salvar as alterações e o site gera um commit, em seu próprio fork, contendo tais alterações. 

Depois é só fazer o PR pelo GitHub mesmo.

Fiz uns testes aqui e parece que contribuir desta forma pode funcionar bem. 
A única "desvantagem" é que uma prévia do documento fica visível publicamente na sua conta no GitBook.

Estou montando um passo a passo de como contribuir desta maneira.

**Comment by walmyrcarvalho** [comment]
Minha idéia era traduzir tudo pelos arquivos .md e depois que tiver uma tag revisada boa a gente sobre pro GitBook. O que acham?

**Comment by FelipeCardoso89** [comment]
Só vi a mensagem do @walmyrcarvalho depois de ter feito o PR.
Pode desconsiderar o PR [#7](https://github.com/CocoaHeadsBrasil/the-swift-programming-language-in-portuguese-br/pull/7) se necessário.

Pelo o que eu vi o CocoaHeads BR não precisa subir o livro para o GitBook até que a versão revisada esteja pronta. As versões do livro que estariam no GitBook seriam somente as de quem optou por contribuir usando o site. Lógico que a única versão confiável, e oficial, seria a do livro que estiver sob a conta da CocoaHeads BR no GitBook.com.

Eu não tinha o NPM instalado na minha máquina quando segui as primeiras instruções do README, então fui ver, por curiosidade, se havia outro meio de contribuição e sujeri este através do site do GitBook.

**Comment by walmyrcarvalho** [comment]
@FelipeCardoso89 Não, que isso, pode manter o PR, o que eu comentei foi mais uma sugestão mesmo! :) Acho que as duas formas são válidas, o importante é colaborar, o que importa é ter os arquivos traduzidos e revisados, depois alinhamos esse lance de colocar ou não no site, até porque vai envolver mais gente.

**Comment by Viniciuscarvalho** [comment]
@FelipeCardoso89 Estamos vendo as possibilidades de como melhor contribuir, por isso toda sugestão agora é bem vinda. Agora a questão é, usar o Gitbook ou modificar os arquivos .md?

**Comment by FelipeCardoso89** [comment]
A proposta é modificar os arquivos .md através do GitBook. 

Na interface de edição do livro existe uma ["file tree"](https://github.com/FelipeCardoso89/the-swift-programming-language-in-portuguese-br/blob/master/artes/project/tutorials/gitbook_web/figura_12.png)  que mostra os arquivos .md, lá é possível criar/apagar/renomear e editar o conteúdo dos arquivos .md

**Comment by Viniciuscarvalho** [comment]
@FelipeCardoso89 estamos vendo como vai ser a estrutura de contribuição e por enquanto vamos segurar o teu PR, tudo bem?

**Comment by FelipeCardoso89** [comment]
Sem problema.

**Comment by FelipeCardoso89** [comment]
@Viniciuscarvalho / @walmyrcarvalho podem excluir o PR https://github.com/CocoaHeadsBrasil/the-swift-programming-language-in-portuguese-br/pull/7? O conteúdo não está correto e vou excluir o branch dele no meu fork, fechem essa issue também se possível. Obrigado.

**Comment by walmyrcarvalho** [comment]
@Viniciuscarvalho Tem certeza? A gente só se organizando pra deixar a contribuição independente do GitBook, mas se quiser podemos apagar.

**Comment by FelipeCardoso89** [comment]
Sim, tenho. Eu errei na configuração do Webhook no passo a passo. No futuro eu escrevo outro se necessário. :)

**Comment by walmyrcarvalho** [comment]
@FelipeCardoso89 eu ia sugerir de você revisar com calma esses ajustes e colocar na Wiki do projeto, acho que é bem válido sim. :)

**Comment by barbosa** [comment]
@FelipeCardoso89 Vou fechar então. O PR vai continuar aqui na aba "closed". Se precisar consultar alguma coisa dele para depois passar pro wiki, é só olhar lá, OK?

cc @walmyrcarvalho @Viniciuscarvalho
