### ISSUE TITLE
Atualizar link do livro

### ISSUE THREAD

**Issue by walmyrcarvalho** [CocoaHeadsBrasil/the-swift-programming-language-in-portuguese-br#6]
Link correto: https://swift.org/documentation/TheSwiftProgrammingLanguage(Swift2.2).epub

**Comment by barbosa** [comment]
No `README.md`?

**Comment by walmyrcarvalho** [comment]
Isso, coloquei um TODO porque tava fazendo pelo celular e não consegui pegar o link certo na hora.
